name: .NET

on:
  schedule:
    - cron: "0 0 * * 6"
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Explanation'     
        required: true
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run
      env:
        IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
      run: dotnet run --no-build --verbosity normal
    - name: Update resources
      uses: test-room-7/action-update-file@v1
      with:
        file-path: out/*
        commit-msg: ":construction_worker: github action auto update"
        github-token: ${{ secrets.GITHUB_TOKEN }}
